# Embed a binary file as a C++ array compiled into a target.
#
# embed_binary(<target> <symbol> <input_file>)
#
# Generates a .cpp in the build dir defining:
#   extern "C" const unsigned char <symbol>_data[];
#   extern "C" const unsigned int  <symbol>_size;
# and adds it to <target>'s sources.
function(embed_binary target symbol input_file)
    set(_out "${CMAKE_CURRENT_BINARY_DIR}/embed_${symbol}.cpp")
    set(_stamp "${CMAKE_CURRENT_BINARY_DIR}/embed_${symbol}.stamp")

    if(NOT EXISTS "${_stamp}" OR "${input_file}" IS_NEWER_THAN "${_stamp}" OR NOT EXISTS "${_out}")
        file(READ "${input_file}" _hex HEX)
        string(LENGTH "${_hex}" _hexlen)
        math(EXPR _bytes "${_hexlen} / 2")
        string(REGEX REPLACE "(..)" "0x\\1," _array "${_hex}")
        file(WRITE "${_out}"
            "// Generated by embed_binary.cmake. Do not edit.\n"
            "extern \"C\" const unsigned char ${symbol}_data[] = {${_array}};\n"
            "extern \"C\" const unsigned int  ${symbol}_size = ${_bytes}u;\n"
        )
        file(TOUCH "${_stamp}")
    endif()

    target_sources(${target} PRIVATE "${_out}")
endfunction()
